### PR TITLE
Cu 860rc67a2 wappin v2 implement wappin v2 in GitHub library

### PR DESCRIPTION
**Pull request by asqolani-flip**
## New Feature
- Login
- Send Message Template
- Unit test and Integration test included

### CODE REVIEW

**Review by sagungwijaya — APPROVED** [review]

**Comment by pianzm** [comment]
As this is a public repository, I suggest not making dependencies into the internal package such as go-core

**Comment by asqolani-flip** [comment]
> As this is a public repository, I suggest not making dependencies into the internal package such as go-core

currently for the go-core used for logging only mas, do you have any suggestion? do we need to remove it mas?

**Comment by pianzm** [comment]
> > As this is public repository, I suggest not to make dependencies into internal package such as go-core
> 
> currently for the go-core used for logging only mas, do you have any suggestion? do we need to remove it mas?

As the purpose is only to log, we can utilize go built-in log function

**Comment by asqolani-flip** [comment]
> > > As this is public repository, I suggest not to make dependencies into internal package such as go-core
> > 
> > 
> > currently for the go-core used for logging only mas, do you have any suggestion? do we need to remove it mas?
> 
> As the purpose is only to log, we can utilize go built-in log function

with this https://pkg.go.dev/log ya mas?

**Comment by pianzm** [comment]
> 

Yes

**Comment by asqolani-flip** [comment]
> > 
> 
> Yes

done mas

**Review by pianzm — APPROVED** [review]

**Pull request merged**
